# See https://pre-commit.com/ for usage and config
repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: pipenv run isort
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: pipenv run black .
    types: [python]

  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: pipenv run flake8
    types: [python]
    exclude: setup.py

  - id: mypy
    name: mypy
    stages: [commit]
    language: system
    entry: pipenv run mypy
    types: [python]
    require_serial: true

  - id: bandit
    name: bandit
    stages: [commit]
    language: system
    entry: pipenv run bandit -c .bandit.yaml
    types: [python]
    require_serial: true

  - id: pycodestyle
    name: pycodestyle
    stages: [commit]
    language: system
    entry: pipenv run pycodestyle
    types: [python]
    require_serial: true

  - id: dodgy
    name: dodgy
    stages: [commit]
    language: system
    entry: pipenv run dodgy
    types: [python]
    require_serial: true

  - id: radon
    name: radon
    stages: [commit]
    language: system
    entry: pipenv run radon cc PRiSM
    types: [python]
    require_serial: true

  - id: pytest
    name: pytest
    stages: [commit]
    language: system
    entry: pipenv run pytest
    types: [python]
    pass_filenames: false

  - id: pytest-cov
    name: pytest-cov
    stages: [commit]
    language: system
    entry: pipenv run pytest --cov backend --cov-fail-under=10 # --cov-fail-under=100
    types: [python]
    pass_filenames: false
